<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup Label="Application">
      <PackageVersion Include="ModelContextProtocol" Version="2.0.0" />
      <PackageVersion Include="ModelContextProtocol.AspNetCore" Version="2.0.0" />
      <PackageVersion Include="JetBrains.Annotations" Version="2026.2.0" />
  </ItemGroup>
</Project>
