<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RuntimeIdentifiers>win-x64;win-arm64;osx-arm64;linux-x64;linux-arm64;linux-musl-x64</RuntimeIdentifiers>
        <OutputType>Exe</OutputType>
        <PackAsTool>true</PackAsTool>
        <PackageType>McpServer</PackageType>
        <SelfContained>true</SelfContained>
        <PublishSelfContained>true</PublishSelfContained>
        <PublishSingleFile>true</PublishSingleFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageId>ai-raccon</PackageId>
        <PackageVersion>0.1.0-beta</PackageVersion>
        <PackageTags>AI; MCP; server; stdio; http; sqlite; agent; memory; vector; rag</PackageTags>
        <Description>An MCP server that will expose memory API for your agent</Description>
    </PropertyGroup>

    <ItemGroup>
        <None Include=".mcp\server.json" Pack="true" PackagePath="/.mcp/"/>
        <None Include="README.md" Pack="true" PackagePath="/"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations"/>
        <PackageReference Include="Microsoft.Extensions.Hosting"/>
        <PackageReference Include="ModelContextProtocol"/>
    </ItemGroup>

</Project>
