using Xunit;

namespace AiRaccoon.Tests.BDD.Features_Code_Corpus;

/// <summary>
///     Partial declaration binding the generated CodeCorpusFeature scenarios into the serialized
///     collection — the generated .feature.cs is regenerated by Reqnroll on build, so the
///     attribute must live here, not in the generated file.
/// </summary>
[Collection(CodeCorpusCollection.Name)]
public partial class CodeCorpusFeature;
