using Xunit;

namespace AiRaccoon.Tests.BDD.Features_File_Watcher;

/// <summary>
///     Partial declaration binding the generated FileWatcherFeature scenarios into the
///     serialized collection — the generated .feature.cs is regenerated by Reqnroll on
///     build, so the attribute must live here, not in the generated file.
/// </summary>
[Collection(FileWatcherCollection.Name)]
public partial class FileWatcherFeature;
