using Xunit;

namespace AiRaccoon.Tests.BDD.Features_Single_Project_Id;

/// <summary>
///     Partial declaration binding the generated SingleProjectId feature scenarios into the
///     serialized collection — the generated .feature.cs is regenerated by Reqnroll on
///     build, so the attribute must live here, not in the generated file. The scan scenario
///     drives the same real FileSystemWatcher pipeline as the file-watcher feature and would
///     flake under full-suite parallel load (Class B flake) without this.
/// </summary>
[Collection(FileWatcherCollection.Name)]
public partial class SingleProjectIdAir_MergeRepairEnforcementFeature;
