#!/usr/bin/env python3
"""Runs all 35 baseline queries against AiRaccoon's memory.db and outputs baseline results JSON.

Usage:
    python3 scripts/run-baseline-queries.py

Requires:
    - AiRaccoon MCP server running at http://localhost:8080/mcp (MCP_TRANSPORT=http)
    - scripts/baseline-queries.json (query definitions)
    - scripts/chunk-hash-map.json (generated by ingest-jsaa-docs.py, for isExpectedSource matching)
"""

import asyncio
import hashlib
import json
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import httpx

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT = "job-search-ai-assistant"
MCP_URL = "http://localhost:5000/mcp"
BATCH_SIZE = 50


class AiRaccoonClient:
    """Lightweight async JSON-RPC client for AiRaccoon MCP server over HTTP."""

    def __init__(self, base_url: str = MCP_URL):
        self.base_url = base_url
        self._client: httpx.AsyncClient | None = None
        self._request_id = 0

    async def __aenter__(self):
        self._client = httpx.AsyncClient(timeout=httpx.Timeout(120.0))
        return self

    async def __aexit__(self, *args):
        if self._client:
            await self._client.aclose()

    async def _call(self, tool_name: str, arguments: dict) -> dict:
        self._request_id += 1
        payload = {
            "jsonrpc": "2.0",
            "id": self._request_id,
            "method": "tools/call",
            "params": {"name": tool_name, "arguments": arguments},
        }
        assert self._client is not None
        t0 = time.monotonic()
        resp = await self._client.post(self.base_url, json=payload)
        resp.raise_for_status()
        elapsed = time.monotonic() - t0
        # AiRaccoon MCP Streamable HTTP returns SSE: "event: message\ndata: {...}\n\n"
        text_body = resp.text
        if "event:" in text_body and "data:" in text_body:
            data_line = next((line.removeprefix("data: ").strip()
                              for line in text_body.splitlines()
                              if line.startswith("data: ")), "{}")
            data = json.loads(data_line)
        else:
            data = resp.json()
        if "error" in data:
            raise RuntimeError(f"RPC error from {tool_name}: {data['error']}")
        content = data.get("result", {}).get("content", [])
        text = content[0].get("text", "{}") if content else "{}"
        print(f"  {tool_name}: {elapsed:.1f}s")
        return json.loads(text)

    async def memory_stats(self) -> dict:
        return await self._call("memory_stats", {"projectId": PROJECT})

    async def memory_search(self, query: str, scope: str = "project",
                            limit: int = 5, min_score: float = 0.0) -> dict:
        return await self._call("memory_search", {
            "projectId": PROJECT, "query": query, "scope": scope,
            "limit": limit, "minScore": min_score,
        })


def compute_expected_hash(content: str) -> str:
    """Mirrors AiRaccoon's ContentHash.Of + WritePathFor formula."""
    assigned_path = hashlib.sha256(content.encode("utf-8")).hexdigest() + ".md"
    combined = assigned_path.encode("utf-8") + content.encode("utf-8")
    return hashlib.sha256(combined).hexdigest()


def load_hash_map() -> dict[str, str]:
    path = SCRIPT_DIR / "chunk-hash-map.json"
    if not path.exists():
        print(f"Warning: {path} not found — isExpectedSource detection disabled")
        return {}
    with open(path) as f:
        return json.load(f)


async def main():
    queries_path = SCRIPT_DIR / "baseline-queries.json"
    if not queries_path.exists():
        print(f"Error: {queries_path} not found")
        sys.exit(1)

    with open(queries_path) as f:
        queries = json.load(f)

    print(f"Loaded {len(queries)} queries from {queries_path}")

    hash_map = load_hash_map()
    if hash_map:
        print(f"Loaded {len(hash_map)} chunk hashes for isExpectedSource detection")
    else:
        print("No hash map — isExpectedSource will always be false")

    results: dict[str, dict] = {}
    matches_at_top3 = 0
    total_with_results = 0

    async with AiRaccoonClient() as client:
        for q in queries:
            qid = q["id"]
            query_text = q["query"]
            expected_source = q.get("expectedSource")
            negative = q.get("negativeTest", False)

            print(f"\n[{qid}] {query_text[:80]}...")

            try:
                search_result = await client.memory_search(
                    query=query_text, scope=q.get("scope", "project"),
                    limit=q.get("searchLimit", 5),
                )
            except Exception as e:
                print(f"  ERROR: {e}")
                results[qid] = {
                    "query": query_text,
                    "category": q.get("category", ""),
                    "expectedSource": expected_source,
                    "expectedKnowledge": q.get("expectedKnowledge", ""),
                    "results": [],
                    "error": str(e),
                }
                continue

            raw_results = search_result.get("results", [])
            mapped = []
            for i, r in enumerate(raw_results):
                is_expected = False
                if not negative and expected_source and hash_map:
                    expected_hash = hash_map.get(expected_source)
                    if expected_hash and r.get("hash") == expected_hash:
                        is_expected = True

                mapped.append({
                    "rank": i + 1,
                    "hash": r.get("hash", ""),
                    "ranking": r.get("ranking", 0),
                    "path": r.get("path", ""),
                    "snippet": r.get("snippet", ""),
                    "isExpectedSource": is_expected,
                })

            if mapped:
                total_with_results += 1
                if not negative:
                    top3_match = any(r["isExpectedSource"] for r in mapped[:3])
                    if top3_match:
                        matches_at_top3 += 1
                        print(f"  ✓ Found expected source at rank ≤3")

            results[qid] = {
                "query": query_text,
                "category": q.get("category", ""),
                "expectedSource": expected_source,
                "expectedKnowledge": q.get("expectedKnowledge", ""),
                "results": mapped,
            }

    baseline = {
        "projectId": PROJECT,
        "ingestedAt": datetime.now(timezone.utc).isoformat(),
        "queryCount": len(queries),
        "queriesWithResults": total_with_results,
        "expectedSourceMatchesAtTop3": matches_at_top3,
        "queryResults": results,
    }

    output_path = SCRIPT_DIR / "baseline-results.json"
    with open(output_path, "w") as f:
        json.dump(baseline, f, indent=2)

    print(f"\n{'='*50}")
    print(f"Done: {total_with_results}/{len(queries)} queries returned results")
    print(f"Expected source matches at rank ≤3: {matches_at_top3}/{len(queries) - sum(1 for q in queries if q.get('negativeTest'))}")
    print(f"Baseline written to {output_path}")

    if matches_at_top3 < 25:
        print(f"WARNING: Only {matches_at_top3} expected-source matches — gate requires ≥25")
        sys.exit(1)


if __name__ == "__main__":
    asyncio.run(main())
