using System.Buffers.Binary;
using System.Security.Cryptography;
using System.Text.Encodings.Web;
using System.Text.Json;
using AiRaccoon.Infrastructure.Embedding;
using Microsoft.Extensions.AI;

namespace AiRaccoon.Tests.Integration;

/// <summary>
///     Committed query vectors for the retrieval sweeps, so their metrics stop being a function of
///     the host CPU (docs/adr/0050, option 1 of docs/adr/0049). Regenerated by
///     <see cref="GateQueryVectorRegenerationTool" />; never ground truth — see the fixture's own note.
/// </summary>
internal static class PinnedQueryVectors
{
    public const string FileName = "gate-query-vectors.json";

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        WriteIndented = true,
        // The query text is the fixture's lookup key; escaped as ' it is unreadable in review.
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
    };

    /// <summary>The fixture beside the test host; the csproj copies it to the output directory.</summary>
    public static string ResourcePath => Path.Combine(AppContext.BaseDirectory, "Resources", FileName);

    /// <summary>The tracked copy the regeneration tool overwrites.</summary>
    public static string SourcePath => Path.Combine(
        Path.GetDirectoryName(TestData.RepoFile("AiRaccoon.slnx"))!, "tests", "AiRaccoon.Tests", "Resources", FileName);

    public static PinnedQueryVectorFile Load() => Load(ResourcePath);

    public static PinnedQueryVectorFile Load(string path)
    {
        if (!File.Exists(path))
        {
            throw new FileNotFoundException(
                $"Pinned query-vector fixture not found at '{path}'. Regenerate it with " +
                $"{GateQueryVectorRegenerationTool.RunEnvVar}=1 (docs/adr/0050).", path);
        }

        return JsonSerializer.Deserialize<PinnedQueryVectorFile>(File.ReadAllText(path), JsonOptions)
               ?? throw new InvalidOperationException($"Pinned query-vector fixture at '{path}' deserialized to null.");
    }

    public static string Write(PinnedQueryVectorFile file, string path)
    {
        File.WriteAllText(path, JsonSerializer.Serialize(file, JsonOptions));
        return path;
    }

    /// <summary>An <see cref="IEmbeddingService" /> that answers only from the committed fixture.</summary>
    public static IEmbeddingService EmbeddingService() => new PinnedQueryEmbeddingService(Load());

    public static IEmbeddingService EmbeddingService(PinnedQueryVectorFile file) =>
        new PinnedQueryEmbeddingService(file);

    /// <summary>Little-endian float32 round-trip: the fixture stores the exact bits the model produced.</summary>
    public static string Encode(ReadOnlySpan<float> vector)
    {
        var bytes = new byte[vector.Length * sizeof(float)];
        for (var i = 0; i < vector.Length; i++)
        {
            BinaryPrimitives.WriteSingleLittleEndian(bytes.AsSpan(i * sizeof(float)), vector[i]);
        }

        return Convert.ToBase64String(bytes);
    }

    public static float[] Decode(string base64)
    {
        var bytes = Convert.FromBase64String(base64);
        var vector = new float[bytes.Length / sizeof(float)];
        for (var i = 0; i < vector.Length; i++)
        {
            vector[i] = BinaryPrimitives.ReadSingleLittleEndian(bytes.AsSpan(i * sizeof(float)));
        }

        return vector;
    }

    /// <summary>Same digest <see cref="PlatformNumericsProbe" /> prints, so probe output and fixture compare by eye.</summary>
    public static string Fingerprint(string base64) =>
        Convert.ToHexString(SHA256.HashData(Convert.FromBase64String(base64)));
}

/// <summary>Provenance plus one entry per query in scripts/baseline-queries.json.</summary>
internal sealed record PinnedQueryVectorFile(
    string Note,
    string GeneratedOn,
    string ArithmeticPath,
    string Runtime,
    string ModelSha256,
    string VocabSha256,
    int Dimension,
    IReadOnlyList<PinnedQueryVector> Vectors);

internal sealed record PinnedQueryVector(string Id, string Query, string Sha256, string Vector);

/// <summary>
///     Answers embedding requests from the committed fixture and throws on any text it does not
///     carry — a query the catalog changed can never be silently re-embedded live.
/// </summary>
internal sealed class PinnedQueryEmbeddingService(PinnedQueryVectorFile file) : IEmbeddingService
{
    private readonly PinnedGenerator _generator = new(file);

    public IEmbeddingGenerator<string, Embedding<float>> CreateGenerator(EmbeddingSettings settings)
    {
        ArgumentNullException.ThrowIfNull(settings);
        return _generator;
    }

    /// <summary>Pinned vectors are keyed by the exact query text, so trimming here would miss every pin.</summary>
    public string TrimQueryToWindow(EmbeddingSettings settings, string query) => query;

    private sealed class PinnedGenerator : IEmbeddingGenerator<string, Embedding<float>>
    {
        private readonly Dictionary<string, float[]> _byQuery;

        public PinnedGenerator(PinnedQueryVectorFile file)
        {
            ArgumentNullException.ThrowIfNull(file);
            _byQuery = file.Vectors.ToDictionary(
                v => v.Query, v => PinnedQueryVectors.Decode(v.Vector), StringComparer.Ordinal);
        }

        public Task<GeneratedEmbeddings<Embedding<float>>> GenerateAsync(IEnumerable<string> values,
            EmbeddingGenerationOptions? options = null, CancellationToken cancellationToken = default)
        {
            ArgumentNullException.ThrowIfNull(values);
            var items = values.ToList();
            var embeddings = new GeneratedEmbeddings<Embedding<float>>(items.Count);
            foreach (var text in items)
            {
                if (!_byQuery.TryGetValue(text, out var vector))
                {
                    throw new KeyNotFoundException(
                        $"No pinned vector for '{text}'. This fixture only covers scripts/baseline-queries.json; " +
                        $"regenerate it with {GateQueryVectorRegenerationTool.RunEnvVar}=1 (docs/adr/0050).");
                }

                embeddings.Add(new Embedding<float>(vector));
            }

            return Task.FromResult(embeddings);
        }

        public void Dispose()
        {
        }

        object? IEmbeddingGenerator.GetService(Type serviceType, object? serviceKey) => null;
    }
}
