using AiRaccoon.Core.Ingestion;
using Shouldly;
using Xunit;

namespace AiRaccoon.Tests.Unit.Ingestion;

/// <summary>
///     P2-B (docs/work/2026-09-23-code-retrieval-eval-plan.md §P2): <see cref="IdentifierSplitter.Split" />
///     must match the Python reference `split_identifier`
///     (scripts/src/retrieval_tuning/code_corpus.py) byte-for-byte — every row below was generated by
///     running that function, not guessed from the boundary rules independently.
/// </summary>
[Trait(TestCategories.Category, TestCategories.Unit)]
[Trait(TestCategories.Speed, TestCategories.Fast)]
public sealed class IdentifierSplitterTests
{
    [Theory]
    [InlineData("WatchOverlapResolver", new[] { "watch", "overlap", "resolver" })]
    [InlineData("HTTPServer2", new[] { "http", "server", "2" })]
    [InlineData("snake_case_name", new[] { "snake", "case", "name" })]
    [InlineData("kebab-case", new[] { "kebab", "case" })]
    [InlineData("a.b.c", new[] { "a", "b", "c" })]
    [InlineData("x", new[] { "x" })]
    [InlineData("ABC", new[] { "abc" })]
    [InlineData("getHTTPResponseCode", new[] { "get", "http", "response", "code" })]
    [InlineData("v2Beta", new[] { "v", "2", "beta" })]
    [InlineData("IDNumber2Class", new[] { "id", "number", "2", "class" })]
    [InlineData("XMLHttpRequest", new[] { "xml", "http", "request" })]
    [InlineData("already_snake", new[] { "already", "snake" })]
    [InlineData("ABTest", new[] { "ab", "test" })]
    [InlineData("iOS", new[] { "i", "os" })]
    [InlineData("v10", new[] { "v", "10" })]
    [InlineData("2Cool4School", new[] { "2", "cool", "4", "school" })]
    [InlineData("__init__", new[] { "init" })]
    [InlineData("COVID19Response", new[] { "covid", "19", "response" })]
    [InlineData("parseJSON5", new[] { "parse", "json", "5" })]
    [InlineData("", new string[0])]
    [InlineData("___", new string[0])]
    [InlineData("A", new[] { "a" })]
    [InlineData("HTTP", new[] { "http" })]
    [InlineData("Server2Name", new[] { "server", "2", "name" })]
    public void Split_MatchesThePythonReference(string name, string[] expected)
    {
        IdentifierSplitter.Split(name).ShouldBe(expected);
    }

    [Fact]
    public void Identifiers_KeepsOnlyMultiPartTokens_SpaceJoinedOnePerLine()
    {
        var result = IdentifierSplitter.Identifiers("sealed class WatchOverlapResolver { void x() {} }");

        result.ShouldBe("watch overlap resolver");
    }

    [Fact]
    public void Identifiers_DedupesRepeatedIdentifiersWithinTheChunk()
    {
        var result = IdentifierSplitter.Identifiers("WatchOverlapResolver WatchOverlapResolver");

        result.ShouldBe("watch overlap resolver");
    }

    [Fact]
    public void Identifiers_DropsSinglePartTokens()
    {
        var result = IdentifierSplitter.Identifiers("class Foo { int x; }");

        result.ShouldBe("");
    }

    [Fact]
    public void Identifiers_JoinsMultipleKeptTokensWithNewlines()
    {
        var result = IdentifierSplitter.Identifiers("WatchOverlapResolver getHTTPResponseCode");

        result.ShouldBe("watch overlap resolver\nget http response code");
    }
}
