"""Regenerate the committed retrieval corpora from a pinned bank copy (P3 AC3).

Exit-code contract (surfaced by scripts/refresh-retrieval-corpora.py):

  0 clean             — every corpus regenerated byte-identically; anchors resolve
  1 anchor drift      — a generator's anchor no longer resolves in the copy
  2 snapshot mismatch — a corpus's pinned header snapshotSha256 != the copy sha
  3 smoke regression  — regenerated bytes differ from the committed artifact,
                        or the regenerated shape fails its smoke check

Determinism: the generators are fixed-seed with stable sorts; this module adds
no timestamps anywhere (the report is byte-stable for the same inputs).
Anchor re-verification happens after generation and fails loud — a corpus is
never reported clean on anchors the copy cannot resolve.

The corpus registry is injectable (`specs=`), so the exit-code contract is
testable on fixture banks without touching the real generators.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from . import corpus, corpus_anchors

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_CORPORA_DIR = REPO_ROOT / "scripts" / "retrieval_tuning" / "corpora"

# Ranking for the overall exit: a precondition failure outranks bad data,
# which outranks a stale committed artifact, which is outranked by clean.
_STATUS_RANK = {"snapshot-mismatch": 0, "anchor-drift": 1,
                "smoke-regression": 2, "clean": 3}
_STATUS_EXIT = {"clean": 0, "anchor-drift": 1, "snapshot-mismatch": 2,
                "smoke-regression": 3}


@dataclass(frozen=True)
class CorpusSpec:
    """One committed corpus and the generator that reproduces it."""

    name: str
    generate: Callable[[Path, Path], object]
    anchor_style: str  # "hash-only" (project corpus) | "eval" (expectedSource)
    expected_count: int | None = None


def snapshot_sha_of(committed: Path) -> str | None:
    """The copy sha a committed corpus pins (header.snapshotSha256), if any."""
    payload = json.loads(committed.read_text())
    if isinstance(payload, dict):
        header = payload.get("header")
        if isinstance(header, dict) and isinstance(header.get("snapshotSha256"), str):
            return header["snapshotSha256"]
    return None


def _queries_of(generated) -> list[dict]:
    return generated["queries"] if isinstance(generated, dict) else list(generated)


def verify_anchors(entries: list[dict], copy_path: Path, style: str) -> list[str]:
    """Re-resolve every anchor in the regenerated entries against the copy.

    hash-only: project-corpus contract — exact expectedHash (one row) plus a
    verbatim contentMarker unique inside its project/scope bucket. eval:
    expectedSource/expectedHash resolution (the corpus validator's own rules).
    """
    if style == "eval":
        return corpus.resolve_anchors(entries, copy_path)
    if style != "hash-only":
        raise ValueError(f"unknown anchor style {style!r}")
    conn = corpus_anchors.open_copy(copy_path)
    problems: list[str] = []
    try:
        for entry in entries:
            expected = entry.get("expectedHash")
            if expected and corpus_anchors.hash_row_count(conn, expected) != 1:
                problems.append(
                    f"{entry.get('id')}: expectedHash {expected[:16]}... is not a "
                    "unique copy row")
            marker = entry.get("contentMarker")
            if marker:
                n = len(corpus_anchors.marker_matches(
                    conn, marker, project_id=entry.get("targetProjectId"),
                    scope=entry.get("targetScope")))
                if n != 1:
                    problems.append(
                        f"{entry.get('id')}: contentMarker resolves to {n} rows "
                        "(must be exactly 1)")
    finally:
        conn.close()
    return problems


def _empty_record(spec: CorpusSpec, committed: Path, regenerated: Path) -> dict:
    return {"name": spec.name, "status": "clean", "problems": [],
            "committedPath": str(committed), "regeneratedPath": str(regenerated),
            "committedSha256": None, "regeneratedSha256": None,
            "matchesCommitted": None, "queryCount": None}


def refresh(copy_path, corpora_dir=None, out_dir=None, *, specs=None,
            copy_sha: str | None = None) -> dict:
    """Regenerate every corpus from `copy_path`; returns the refresh report.

    The report carries the overall status + exitCode; the caller maps it to
    sys.exit. The copy is only ever read (the generators open it read-only);
    regeneration lands in out_dir (default: the committed corpora dir).
    """
    copy_path = Path(copy_path)
    if not copy_path.exists():
        raise FileNotFoundError(f"bank copy not found: {copy_path}")
    corpora_dir = Path(corpora_dir) if corpora_dir is not None else DEFAULT_CORPORA_DIR
    out_dir = Path(out_dir) if out_dir is not None else corpora_dir
    if specs is None:
        specs = default_specs()
    copy_sha = copy_sha or corpus_anchors.sha256_file(copy_path)
    out_dir.mkdir(parents=True, exist_ok=True)

    records: list[dict] = []
    for spec in specs:
        committed = corpora_dir / spec.name
        regenerated = out_dir / spec.name
        record = _empty_record(spec, committed, regenerated)
        committed_bytes = committed.read_bytes() if committed.exists() else None
        if committed_bytes is not None:
            record["committedSha256"] = corpus_anchors.sha256_file(committed)
            pin = snapshot_sha_of(committed)
            if pin is not None and pin != copy_sha:
                record["status"] = "snapshot-mismatch"
                record["problems"].append(
                    f"committed corpus pins copy {pin[:12]}... but the refresh copy "
                    f"is {copy_sha[:12]}... — regenerate from the pinned copy or "
                    "update the corpus provenance deliberately")
                records.append(record)
                continue
        try:
            generated = spec.generate(copy_path, regenerated)
        except RuntimeError as exc:
            record["status"] = "anchor-drift"
            record["problems"].append(f"generation refused: {exc}")
            records.append(record)
            continue
        entries = _queries_of(generated)
        record["queryCount"] = len(entries)
        anchor_problems = verify_anchors(entries, copy_path, spec.anchor_style)
        if anchor_problems:
            record["status"] = "anchor-drift"
            record["problems"].extend(anchor_problems)
        if spec.expected_count is not None and len(entries) != spec.expected_count:
            record["problems"].append(
                f"shape smoke failed: {len(entries)} queries, expected {spec.expected_count}")
            if record["status"] == "clean":
                record["status"] = "smoke-regression"
        record["regeneratedSha256"] = corpus_anchors.sha256_file(regenerated)
        record["matchesCommitted"] = (
            committed_bytes is not None
            and regenerated.read_bytes() == committed_bytes)
        if committed_bytes is not None and not record["matchesCommitted"]:
            record["problems"].append(
                "regenerated bytes differ from the committed artifact: the committed "
                "corpus is stale (or was generated from a different copy) — rerun "
                "against its pinned copy, or commit the regenerated artifact")
            if record["status"] == "clean":
                record["status"] = "smoke-regression"
        records.append(record)

    overall = min((r["status"] for r in records), key=lambda s: _STATUS_RANK[s]) \
        if records else "clean"
    report = {
        "copy": str(copy_path),
        "copySnapshotSha256": copy_sha,
        "corporaDir": str(corpora_dir),
        "outDir": str(out_dir),
        "status": overall,
        "exitCode": _STATUS_EXIT[overall],
        "corpora": records,
    }
    (out_dir / "refresh-report.json").write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n")
    return report


def default_specs() -> list[CorpusSpec]:
    """The two live corpora. Heavy generator modules load lazily, so fixture
    tests can call refresh(specs=[...]) without touching them."""
    scripts_dir = REPO_ROOT / "scripts" / "retrieval_tuning"
    if str(scripts_dir) not in sys.path:
        sys.path.insert(0, str(scripts_dir))
    import importlib  # noqa: PLC0415 — lazy by design

    project = importlib.import_module("build_project_corpus")
    eval_corpus = importlib.import_module("build_eval_corpus")
    return [
        CorpusSpec(name="project-corpus-100.json",
                   generate=project.generate, anchor_style="hash-only",
                   expected_count=100),
        CorpusSpec(name="eval-set-100.json",
                   generate=eval_corpus.generate, anchor_style="eval",
                   expected_count=100),
    ]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate the retrieval corpora from a pinned bank copy "
                    "(P3 AC3). Exit codes: 0 clean, 1 anchor drift, "
                    "2 snapshot mismatch, 3 smoke regression.")
    parser.add_argument("--copy",
                        default=os.environ.get("AI_RACCOON_EVAL_COPY"),
                        help="pinned bank copy (default: $AI_RACCOON_EVAL_COPY)")
    parser.add_argument("--corpora-dir", default=str(DEFAULT_CORPORA_DIR),
                        help="where the committed corpora live")
    parser.add_argument("--out-dir", default=None,
                        help="where regenerated corpora + refresh-report.json go "
                             "(default: the corpora dir, in place)")
    args = parser.parse_args(argv)
    if not args.copy:
        parser.error("--copy (or AI_RACCOON_EVAL_COPY) is required")
    try:
        report = refresh(args.copy, args.corpora_dir, args.out_dir)
    except FileNotFoundError as exc:
        print(f"FAIL: {exc}")
        return 2
    for record in report["corpora"]:
        marker = {"clean": "OK", "anchor-drift": "ANCHOR-DRIFT",
                  "snapshot-mismatch": "SNAPSHOT-MISMATCH",
                  "smoke-regression": "SMOKE-REGRESSION"}[record["status"]]
        line = (f"{marker}: {record['name']} "
                f"(queries={record['queryCount']}, "
                f"committed-match={record['matchesCommitted']})")
        print(line)
        for problem in record["problems"]:
            print(f"  - {problem}")
    print(f"refresh: {report['status']} (exit {report['exitCode']}); report: "
          f"{Path(report['outDir']) / 'refresh-report.json'}")
    return report["exitCode"]
